### PR TITLE
Package and publish to pypi

### PR DESCRIPTION
**Pull request by Yannick-Dayer**
This PR refactors the project to make it a Python package, ready for distribution via PyPI.

- Added an `__init__.py` to ensure the project can be recognized as a Python package.
- Fixed the import statements for relative files in the package.
- Added a `pyproject.toml` file to define the build system (using `flit`) and metadata for the package.
- Updated `README.md` to include instructions on installing the package using pip.
- Implemented a GitHub Actions workflow to automate the publishing process. It will trigger at the creation of a new release and automatically publish the package to PyPI.

### CODE REVIEW

**Comment by Yannick-Dayer** [comment]
Who creates the project on PyPI ?

For the current setup, it should be named `raw-speech-classification` (but this name can be changed if needed), and should be set up for trusted publishing from this repository (from the `publish.yml` workflow).

**Comment by Yannick-Dayer** [comment]
> Who creates the project on PyPI ?
> 
> For the current setup, it should be named `raw-speech-classification` (but this name can be changed if needed), and should be set up for trusted publishing from this repository (from the `publish.yml` workflow).

The PyPI project is created, and "pending" in my account. When a release is done on GitHub, it will trigger the action `deploy.yml` which publishes the package to PyPI (it is set to allow this action).

I'll then add the correct members.

**Comment by ocanevet** [comment]
There is an issue in the `pyproject.toml`:

- if the users want the PyTorch backend, they can create the conda env from `conda/rsclf-pytorch.yaml` and running `pip install .` will work
- if the users want the Tensorflow backend, they can create the conda env from `conda/rsclf-tensorflow.yaml`, but running the `pip install .` will install PyTorch

I think that the `torch`, `torchvision`, and `torchaudio` should be removed from the `pyproject.toml` to let the users do what they want.

**Comment by ocanevet** [comment]
Or, we do something like `pip install rsclf[torch]` and `pip install rsclf[tensorflow]`.

**Comment by Yannick-Dayer** [comment]
I can easily enough add two optional dependencies lists so we can install with `[torch]` or `[tensorflow]`, but that means doing only `pip install raw-speech-classification` will not make a working installation.
I have to see if it can be worked around.
Otherwise, I'll write instructions.

**Comment by Yannick-Dayer** [comment]
I separated both frameworks into their own `optional-dependencies` and updated the installation instructions.

**Comment by ocanevet** [comment]
Thanks. The demo code on the `datasets/IEMOCAP/F1_lists` produces the same figure as in the README for both PyTorch and TensorFlow.
Once this is pushed on pypi, maybe we should check the output of `pip install raw-speech-classification[tensorflow]` because I don't know which version of Tensorflow will come. In the pyproject, keras was pinned to 3.4.1 which works with TF 2.16.
Maybe we should check that also with Keras 3.5 and TF.

**Comment by Yannick-Dayer** [comment]
Hmm.
When removing the version pins in `pyproject.toml`, pip installs `keras-3.5.0` and `tensorflow-2.17.0`.
I tried running the training, but it crashed after a few epochs without giving a reason (`2543557 killed  rsclf-train`).

I then tried pinning `keras==3.4.1` and `tensorflow[and-cuda]==2.16.*`, reinstalled and ran again, and it did not crash.

Are some versions of Keras only compatible with some versions of TF?
Or is TF 2.17 too recent and has bugs?

I will now pin these dependencies so that pip installs the same versions as in the conda files.

**Comment by ocanevet** [comment]
I don't know exactly

https://github.com/keras-team/keras/blob/a3b4e2099c824fb0e726d6e87ffa7470dcd9c471/requirements-tensorflow-cuda.txt#L2

There are contractory comments here. I will check on my side.

**Comment by Yannick-Dayer** [comment]
The issue was happening because of a lack of memory. Running with more allocatable memory worked with Keras 3.5 and TF 2.17.

I removed the version pins.

**Review by ocanevet — APPROVED** [review]
Everything is fine. Thanks for the changes.

**Pull request merged**
